# -*- coding: utf-8 -*-

from odoo import models, api

class AccountMove(models.Model):
    _inherit = 'account.move'

    @api.onchange('l10n_latam_document_type_id', 'l10n_latam_document_number', 'partner_id')
    def _inverse_l10n_latam_document_number(self):
        """
        OVERRIDE from l10n_latam_invoice_document.
        This onchange is designed for manual document number entry (e.g., vendor bills),
        but it interferes with the automatic fiscal sequence generation for customer invoices in Honduras.

        This override identifies sequenced Honduran sales documents and prevents the onchange
        from running on them. This allows the invoice 'name' to remain empty until posting,
        ensuring the correct fiscal sequence (with CAI logic) is triggered.
        """
        # Identify records that should NOT use this onchange logic because they need
        # to be numbered by a fiscal sequence during posting.
        sequenced_hn_sales = self.filtered(
            lambda rec: rec.company_id.country_id.code == 'HN' and
            rec.is_sale_document(include_receipts=True) and
            not rec.l10n_latam_manual_document_number
        )

        # For all other records (e.g., vendor bills), apply the original logic from l10n_latam_invoice_document.
        super(AccountMove, self - sequenced_hn_sales)._inverse_l10n_latam_document_number()

        # For the sequenced Honduran sales documents, we do nothing in this onchange.
        # The 'name' will be generated by the fiscal sequence during the _post() method.
